version: '3.8'

# Reusable configuration anchors
x-common-restart: &common-restart
  restart: unless-stopped

x-common-healthcheck-timing: &common-healthcheck-timing
  interval: 10s
  timeout: 5s
  retries: 3

services:
  # Database Service
  mongodb:
    image: mongo:6
    container_name: quickcart-mongodb
    <<: *common-restart
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-quickcart}
    volumes:
      - mongodb_data:/data/db
    networks:
      - quickcart-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      <<: *common-healthcheck-timing

  # Message Broker Coordination Service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: quickcart-zookeeper
    <<: *common-restart
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - quickcart-network

  # Message Broker Service
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: quickcart-kafka
    <<: *common-restart
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - quickcart-network
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092
      <<: *common-healthcheck-timing

volumes:
  mongodb_data:
    driver: local
    name: quickcart-mongodb-data

networks:
  quickcart-network:
    driver: bridge
    name: quickcart-network